name: hampprocenv
channels:
  - conda-forge
  - defaults
  - rttools
dependencies:
  - python==3.12
  - pip
  - numpy
  - pandas
  - scipy
  - matplotlib
  - xarray==2025.1.2
  - netcdf4
  - zarr==2.18.3
  - pyyaml
  - dask
  - numcodecs
  - tqdm
  - ruamel.yaml
  - pyarts
  - pip:
    - orcestra
    - fsspec
    - typhon
    - git+https://github.com/atmtools/pyarts-fluxes
